simulate failure to start
Change-Id: Ic886779ebbd4eb1a1597d115104c8f911f07be45

diff --git a/jobs/batlight/templates/batlight_ctl.erb b/jobs/batlight/templates/batlight_ctl.erb
--- a/jobs/batlight/templates/batlight_ctl.erb
+++ b/jobs/batlight/templates/batlight_ctl.erb
@@ -16,6 +16,11 @@ RUNAS=vcap
 
 case $1 in
 
+  # simulate failure if properties.batlight.fail is set
+  if [ ! -z "<%= properties.batlight.fail if properties.batlight %>" ]; then
+    exit 1
+  fi
+
   start)
     mkdir -p $RUN_DIR $LOG_DIR $STORE_DIR
     chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $STORE_DIR
